// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your API KEY',
    appId: '1:985477721279:web:abd7bfb351361a234e2a0a',
    messagingSenderId: '985477721279',
    projectId: 'friuts-app',
    authDomain: 'friuts-app.firebaseapp.com',
    storageBucket: 'friuts-app.firebasestorage.app',
    measurementId: 'G-Y2TY2Y6EBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your API KEY',
    appId: '1:985477721279:android:bf857a1273141aa94e2a0a',
    messagingSenderId: '985477721279',
    projectId: 'friuts-app',
    storageBucket: 'friuts-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your API KEY',
    appId: '1:985477721279:ios:6642924cd1c2038c4e2a0a',
    messagingSenderId: '985477721279',
    projectId: 'friuts-app',
    storageBucket: 'friuts-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8nFkJdoRZBmqWqiEUq2KsgRQqwdPnTs',
    appId: '1:985477721279:ios:6642924cd1c2038c4e2a0a',
    messagingSenderId: '985477721279',
    projectId: 'friuts-app',
    storageBucket: 'friuts-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitsEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMMVCc0nMHvzn8S7SARngZImCYLRtJ2oY',
    appId: '1:985477721279:web:6486c00da3290c2a4e2a0a',
    messagingSenderId: '985477721279',
    projectId: 'friuts-app',
    authDomain: 'friuts-app.firebaseapp.com',
    storageBucket: 'friuts-app.firebasestorage.app',
    measurementId: 'G-W7JCG4P86X',
  );
}
